### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by David-MacD** [sprintstars/hummingbird#8]
Create a database to persist our component statuses.

- It should come with a couple of scripts to reset and seed it during development. We can think about using different tables for dev.
- The schema should now reflect a history of changes if that wasn't the case already

It was decided that we would go for Vercel's Postgres offering.

- [x] ERD
- [x] script for seeder (package.json)
- [x] create database folder in repo
- [x] init the tables (seeder. js file)
- [x] populate tables 
- [x] check that connected and populated correctly
- [x] UPDATE hardcode into route file
- [x] DELETE hardcode into route file
- [ ] POST route (for component creation)

**Comment by Satty90** [comment]
Partly done. We will try to do simple Auth in parallel with db

**Comment by David-MacD** [comment]
Switched to Supabase Postgres to take advantage of its easy Auth
