### ISSUE TITLE
Ordering, Filtering, and Grouping of Components

### ISSUE THREAD

**Issue by David-MacD** [sprintstars/hummingbird#9]
Each service Component should have the ability to be ordered or filtered based on its health.
Components may also support labels/tags for visual grouping in the UI.

The default should be no grouping, no filtering and ordered to have bad health on top. ✅

Look at the UX,
Clicking on Fully operational brings healthy to top of list and collapses unhealthy into one lozenge with a number indicating the number of unhealthy components. -- Clicking on that box should then bring unhealthy to top again. 
clicking on "Disruptions" should bring unhealthy to top (if not already at top). 

- [x] find filter bar component

Related tickets are: #28 and #29 
--- create another ticket for grouping

**Comment by Satty90** [comment]
ordering and filtering of the current box is finished and ready to deploy. We are going to implement the a search box
